sudo: false
language: ruby
rvm:
  - 2.3.6
gemfile:
  - gemfiles/sidekiq_3.3.1.gemfile
  - gemfiles/sidekiq_3.x.gemfile
  - gemfiles/sidekiq_4.x.gemfile
  - gemfiles/sidekiq_5.x.gemfile
before_install: gem install bundler -v 1.16.1
script:
  - bundle exec appraisal install
  - bundle exec appraisal rake spec
cache:
  - bundler
